apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-peccy-web
  labels:
    app: service-peccy-web
spec:
  template:
    spec:
      containers:
      - name: service-peccy-web
        image: 727618787612.dkr.ecr.ap-northeast-1.amazonaws.com/eks-cicd-dr_service-peccy-web:commit-2b380976f3ee20509182ab4ed60464cfddc3c2cd
        env:
        - name: AWS_REGION
          value: Tyoko
