apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-peccy-app
  labels:
    app: service-peccy-app
spec:
  template:
    spec:
      containers:
      - name: service-peccy-app
        image: 727618787612.dkr.ecr.ap-northeast-2.amazonaws.com/eks-cicd-dr_service-peccy-app:commit-1a0667c449f7f1293e098082b20bebb814808f68
        env:
        - name: AWS_REGION
          value: Seoul
        - name: MYSQL_URL
          value: eks-cicd-dr-primary-seoul.cluster-cynrd5hzuufh.ap-northeast-2.rds.amazonaws.com

