apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-peccy-app
  labels:
    app: service-peccy-app
spec:
  template:
    spec:
      containers:
      - name: service-peccy-app
        image: 727618787612.dkr.ecr.ap-northeast-1.amazonaws.com/eks-cicd-dr_service-peccy-app:commit-abb13b889fec225f06a7ad348187d305de4d1df2
        env:
        - name: AWS_REGION
          value: Tyoko
        - name: MYSQL_URL
          value: eks-cicd-dr-secondary-tyoko.cluster-ca4yqj6d1yj1.ap-northeast-1.rds.amazonaws.com

