apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-peccy-app
  labels:
    app: service-peccy-app
spec:
  template:
    spec:
      containers:
      - name: service-peccy-app
        image: 727618787612.dkr.ecr.ap-northeast-2.amazonaws.com/eks-cicd-dr_service-peccy-app:commit-63ea8062b21d0fc8401d896a2fe29482195469e1
        env:
        - name: AWS_REGION
          value: tyoko
