apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-peccy-app
  labels:
    app: service-peccy-app
spec:
  template:
    spec:
      containers:
      - name: service-peccy-app
        image: 727618787612.dkr.ecr.ap-northeast-1.amazonaws.com/eks-cicd-dr_service-peccy-app:commit-c43f27b18fc7a4e6b97c58818053f2d555265445
        env:
        - name: AWS_REGION
          value: tyoko
        - name: MYSQL_URL
          value: eks-cicd-dr-secondary-tyoko.cluster-ca4yqj6d1yj1.ap-northeast-1.rds.amazonaws.com

